export const EGYPT_FACTS = [
  'Scarabs stood for Khepri, who rolled the sun across the sky.',
  'The Great Pyramid was Earth’s tallest building for 3,800 years.',
  'Cleopatra lived closer to the moon landing than the Great Pyramid.',
  'Egypt’s 365-day year followed the Nile: flood, growth, harvest.',
  'The word “paper” comes from papyrus, Egypt’s writing reed.',
  'The Rosetta Stone is how we learned to read hieroglyphs.',
  'Egyptian blue is one of the oldest synthetic pigments ever made.',
  'Kohl eyeliner was worn by men and women, as makeup and sun shield.',
  'Pyramid crews were often paid in bread and beer.',
  'Cats were sacred to Bastet — harming one was a serious offense.',
  'Senet is one of the oldest board games we can still reconstruct.',
  'The ankh is the hieroglyph for “life.”',
  'Egyptians mummified people, cats, ibises, and even crocodiles.',
  'Obelisks were sun monuments — a few still stand in European cities.',
  'A royal cubit was roughly the length of a forearm.',
  'Tutankhamun’s tomb sat nearly untouched until 1922.',
  '“Kemet” means the Black Land — named for the Nile’s dark silt.',
  'Scribes trained for years; writing was a fast way up in society.',
  'Nobody is quite sure when the Sphinx lost its nose.',
  'Workers carved crew names like “the Drunkards of Khufu” in the stones.',
  'The Nile is the world’s longest river, running about 6,650 km.',
  'Most pyramids were tombs, not treasure vaults or grain silos.',
  'Pharaohs wore a false beard as a symbol of divine kingship.',
  'Hatshepsut ruled as pharaoh and was often shown with that beard.',
  'Ramesses II reigned about 66 years and built on a colossal scale.',
  'Akhenaten tried to shift worship toward a single sun disk, the Aten.',
  'Nefertiti’s bust is one of the most famous faces from the ancient world.',
  'The Book of the Dead was a guidebook for the afterlife, not a single book.',
  'Hearts were weighed against the feather of Ma’at for a just life.',
  'If the heart was heavy with wrongdoing, Ammit was said to eat it.',
  'Canopic jars held the lungs, liver, stomach, and intestines.',
  'The brain was usually discarded; they thought the heart did the thinking.',
  'Natron, a desert salt, was the key drying agent in mummification.',
  'A full elite mummification could take about 70 days.',
  'Linen wrappings on a mummy could stretch for hundreds of meters.',
  'Wigs were common fashion, and priests often shaved their heads.',
  'Sandals were a status object; many people went barefoot.',
  'Linen was the everyday fabric — light, washable, and desert-proof.',
  'Gold was called “the flesh of the gods” and came mostly from Nubia.',
  'Lapis lazuli in Egyptian jewelry was imported from far-off Afghanistan.',
  'They traded down the Red Sea for incense, ebony, and exotic animals.',
  'Cedar for ships and coffins was imported from Lebanon.',
  'Egyptian ships used the Nile as a north–south highway.',
  'The current runs north; the wind often blows south — perfect for travel.',
  'Giza’s pyramids are aligned to the cardinal points with striking accuracy.',
  'Orion and Sirius mattered: they timed floods, festivals, and burials.',
  'The heliacal rising of Sirius once marked the new year.',
  'Temple floors sloped slightly so Nile water could be used in ritual.',
  'Karnak is one of the largest temple complexes ever built.',
  'Luxor Temple was linked to Karnak by a long sphinx-lined avenue.',
  'Abu Simbel was cut from living rock, then later moved to save it.',
  'The temples of Philae were relocated block by block for the High Dam.',
  'The Step Pyramid of Djoser is the oldest large stone building still standing.',
  'Imhotep, Djoser’s architect, was later remembered as a sage and healer.',
  'Meidum and Dahshur show the trial-and-error that led to true pyramids.',
  'The Bent Pyramid changes angle halfway up — an ancient course correction.',
  'Khufu’s pyramid contains about 2.3 million stone blocks.',
  'Most workers were rotating laborers, not a slave army from Hollywood.',
  'Workers’ villages at Giza had bakeries, infirmaries, and beer vats.',
  'Onions, garlic, fish, and emmer bread were staple foods.',
  'Beer was thick, nutritious, and safer than some standing water.',
  'Dates, figs, and honey were the main sweeteners.',
  'They kept bees and prized honey as medicine and offering.',
  'Board games, wrestling, and river hunting filled festival days.',
  'Hunting in the marshes was sport for nobles and a scene in tombs.',
  'Hippos were dangerous Nile neighbors and symbols of chaotic force.',
  'Crocodiles were feared and, in some towns, worshiped as Sobek.',
  'The ibis was tied to Thoth, god of writing and the moon.',
  'Thoth was said to have invented hieroglyphs.',
  'Horus, the falcon, stood for kingship; Set stood for disorder.',
  'Isis was a magician-goddess and a model of devoted family care.',
  'Osiris ruled the dead; his green skin meant rebirth, not decay.',
  'Ra sailed a sun boat through the underworld every night.',
  'The ouroboros — a snake eating its tail — appears in New Kingdom art.',
  'Cartouches are oval rings that protect a royal name in writing.',
  'Hieroglyphs can face left or right; you read toward the faces.',
  'There was also hieratic, a faster cursive used by working scribes.',
  'Demotic was a still later, even quicker everyday script.',
  'Coptic, written with Greek letters, preserved the last stage of Egyptian.',
  'Champollion announced the decipherment of hieroglyphs in 1822.',
  'Egypt’s first named king is often listed as Narmer, unifier of the Two Lands.',
  'The red crown was Lower Egypt; the white crown was Upper Egypt.',
  'Pharaohs wore the double crown to say they ruled both.',
  'Memphis was an early capital; Thebes later became the religious heart.',
  'Amarna was Akhenaten’s short-lived capital dedicated to the Aten.',
  'Alexandria, founded by Alexander, became a Mediterranean brain trust.',
  'The Library of Alexandria aimed to collect the world’s books.',
  'The Lighthouse of Alexandria was one of the Seven Wonders.',
  'Only the Great Pyramid of the original Seven Wonders still stands.',
  'Egyptians used a base-10 number system and unit fractions.',
  'The Rhind Papyrus is a surviving math workbook of problems and tricks.',
  'They calculated areas of circles and volumes of pyramids and granaries.',
  'A cubit rod was a standardized measuring stick for builders.',
  'Medical papyri describe setting bones, dressing wounds, and dental work.',
  'They stitched cuts, used honey as an antiseptic, and made prosthetics.',
  'Some mummies still have evidence of dental abscesses and arthritis.',
  'Makeup palettes and mirrors were buried so beauty could continue after death.',
  'Tomb walls show what the dead hoped to keep eating forever.',
  'Shabti figurines were stand-in workers for chores in the afterlife.',
  'The Opening of the Mouth rite was meant to restore the senses of the dead.',
  'Pyramids gave way to hidden rock-cut tombs in the Valley of the Kings.',
  'Howard Carter found Tutankhamun after years of nearly giving up.',
  '“Wonderful things” is what Carter said he saw through the tomb doorway.',
  'Most royal tombs were robbed in antiquity; Tut’s is the spectacular exception.',
  'Egyptians loved wordplay; names and puns were a kind of magic.',
  'To erase a person from memory, later kings sometimes chiseled out their names.',
  'Women could own property, run businesses, and take cases to court.',
  'Divorce was legal, and marriage contracts spelled out property rights.',
  'Children played with balls, dolls, and pull-along toy animals.',
  'School was mostly for future scribes; lessons included copying wise sayings.',
  '“Instruction” texts were the self-help books of the Bronze Age.',
  'Perfume oils and incense made temples smell like the gods’ own houses.',
  'Blue lotus and mandrake appear in banquet scenes as party plants.',
  'The desert was “the Red Land,” a place of danger, mines, and tombs.',
  'Faience is a glazed quartz ceramic that could shine like turquoise.',
  'Glassmaking and beadwork were high crafts in New Kingdom workshops.',
  'Chariots arrived in the Second Intermediate Period and changed warfare.',
  'Composite bows and bronze weapons made New Kingdom armies formidable.',
  'Nubia was rival, trading partner, and, at times, the ruling power.',
  'The 25th Dynasty pharaohs were Kushite kings from the south.',
  'Persian, Greek, and Roman empires all took turns ruling Egypt.',
  'Cleopatra VII spoke several languages and was the last Ptolemaic ruler.',
  'After Actium, Egypt became Rome’s grain basket.',
  'Egypt’s last hieroglyphic inscription was carved in 394 CE at Philae.',
  'The modern republic’s flag still carries the colors of old pan-Arab banners.',
  'Today Egypt’s population clusters along the Nile, just as it did in antiquity.',
] as const
